chore(trading): upload market-sim logs

diff --git a/.github/workflows/console-test-run.yml b/.github/workflows/console-test-run.yml
--- a/.github/workflows/console-test-run.yml
+++ b/.github/workflows/console-test-run.yml
@@ -233,15 +233,20 @@ jobs:
       - name: Find Directory
         id: find-dir
         run: |
-          DIR=$(find /tmp -type d -regex ".*/vega-sim-[0-9]+$" -print -quit)
-          if [[ $DIR != "" ]]; then
+          DIR=$(find /tmp -type d -name "vega-sim-*" -print -quit)
+          if [[ -d "$DIR" ]]; then
+            echo "Found directory: $DIR"
             echo "DIR=$DIR" >> $GITHUB_ENV
+          else
+            echo "Directory not found."
+            exit 1
           fi
 
       - name: Compress Files
         if: env.DIR
         run: |
-          tar -czvf ${{ github.workspace }}/market-sim-logs.tar.gz -C $DIR .
+          tar -czvf ${{ github.workspace }}/market-sim-logs.tar.gz -C "$DIR" .
+          echo "Compressed files at ${{ github.workspace }}/market-sim-logs.tar.gz"
 
       - name: Upload Compressed market-sim-logs
         uses: actions/upload-artifact@v3
